// <auto-generated />
using System;
using Chronos.Agenda.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Chronos.Agenda.Infrastructure.Data.EF.Migrations
{
    [DbContext(typeof(ChronosAgendaDbContext))]
    [Migration("20260723112220_AdicionarDiscriminadoresParaOwnedEntities")]
    partial class AdicionarDiscriminadoresParaOwnedEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Chronos.Agenda.Domain.Agendamentos.Entidades.Agendamento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("NomeServicoContratado")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome_servico_contratado");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacao_id");

                    b.Property<Guid>("ProfissionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("profissional_id");

                    b.Property<Guid>("ServicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("servico_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_agendamentos");

                    b.HasIndex("ServicoId")
                        .HasDatabaseName("ix_agendamentos_servico_id");

                    b.HasIndex("OrganizacaoId", "ProfissionalId")
                        .HasDatabaseName("ix_agendamentos_organizacao_id_profissional_id");

                    b.HasIndex("ProfissionalId", "Status")
                        .HasDatabaseName("ix_agendamentos_profissional_id_status");

                    b.ToTable("agendamentos", (string)null);
                });

            modelBuilder.Entity("Chronos.Agenda.Domain.Disponibilidades.Entidades.DisponibilidadeSemanal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DiaDaSemana")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("dia_da_semana");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacao_id");

                    b.Property<Guid>("ProfissionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("profissional_id");

                    b.HasKey("Id")
                        .HasName("pk_disponibilidades_semanais");

                    b.HasIndex("ProfissionalId")
                        .HasDatabaseName("ix_disponibilidades_semanais_profissional_id");

                    b.HasIndex("OrganizacaoId", "ProfissionalId", "DiaDaSemana")
                        .HasDatabaseName("ix_disponibilidades_semanais_organizacao_id_profissional_id_di");

                    b.ToTable("disponibilidades_semanais", (string)null);
                });

            modelBuilder.Entity("Chronos.Agenda.Domain.Organizacoes.Entidades.Organizacao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("Id")
                        .HasName("pk_organizacoes");

                    b.ToTable("organizacoes", (string)null);
                });

            modelBuilder.Entity("Chronos.Agenda.Domain.Profissionais.Entidades.Profissional", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacao_id");

                    b.HasKey("Id")
                        .HasName("pk_profissionais");

                    b.HasIndex("OrganizacaoId")
                        .HasDatabaseName("ix_profissionais_organizacao_id");

                    b.ToTable("profissionais", (string)null);
                });

            modelBuilder.Entity("Chronos.Agenda.Domain.Servicos.Entidades.Servico", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacao_id");

                    b.Property<Guid>("ProfissionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("profissional_id");

                    b.Property<string>("TipoAtendimento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo_atendimento");

                    b.HasKey("Id")
                        .HasName("pk_servicos");

                    b.HasIndex("OrganizacaoId")
                        .HasDatabaseName("ix_servicos_organizacao_id");

                    b.HasIndex("ProfissionalId")
                        .HasDatabaseName("ix_servicos_profissional_id");

                    b.ToTable("servicos", (string)null);
                });

            modelBuilder.Entity("Chronos.Agenda.Infrastructure.Compartilhado.MembroOrganizacao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em_utc");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacao_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_membros_organizacao");

                    b.HasIndex("OrganizacaoId")
                        .HasDatabaseName("ix_membros_organizacao_organizacao_id");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("ix_membros_organizacao_usuario_id");

                    b.ToTable("membros_organizacao", (string)null);
                });

            modelBuilder.Entity("Chronos.Agenda.Infrastructure.Identity.PapelIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Chronos.Agenda.Infrastructure.Identity.UsuarioIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_role_claims_role_id");

                    b.ToTable("role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_claims_user_id");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_logins_user_id");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_tokens");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("Chronos.Agenda.Domain.Agendamentos.Entidades.Agendamento", b =>
                {
                    b.HasOne("Chronos.Agenda.Domain.Organizacoes.Entidades.Organizacao", null)
                        .WithMany()
                        .HasForeignKey("OrganizacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_agendamentos_organizacoes_organizacao_id");

                    b.HasOne("Chronos.Agenda.Domain.Profissionais.Entidades.Profissional", null)
                        .WithMany()
                        .HasForeignKey("ProfissionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_agendamentos_profissionais_profissional_id");

                    b.HasOne("Chronos.Agenda.Domain.Servicos.Entidades.Servico", null)
                        .WithMany()
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_agendamentos_servicos_servico_id");

                    b.OwnsOne("Chronos.Agenda.Domain.Compartilhado.ObjetosValor.Auditoria", "Auditoria", b1 =>
                        {
                            b1.Property<Guid>("AgendamentoId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("AtualizadoEmUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("atualizado_em_utc");

                            b1.Property<DateTime>("CriadoEmUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("criado_em_utc");

                            b1.HasKey("AgendamentoId");

                            b1.ToTable("agendamentos");

                            b1.WithOwner()
                                .HasForeignKey("AgendamentoId")
                                .HasConstraintName("fk_agendamentos_agendamentos_id");
                        });

                    b.OwnsOne("Chronos.Agenda.Domain.Servicos.ObjetosValor.PrecoServico", "PrecoCobrado", b1 =>
                        {
                            b1.Property<Guid>("AgendamentoId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("preco_cobrado");

                            b1.HasKey("AgendamentoId");

                            b1.ToTable("agendamentos");

                            b1.WithOwner()
                                .HasForeignKey("AgendamentoId")
                                .HasConstraintName("fk_agendamentos_agendamentos_id");
                        });

                    b.OwnsOne("Chronos.Agenda.Domain.Agendamentos.ObjetosValor.LocalAtendimento", "Local", b1 =>
                        {
                            b1.Property<Guid>("AgendamentoId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("local_tipo");

                            b1.HasKey("AgendamentoId");

                            b1.ToTable("agendamentos");

                            b1.WithOwner()
                                .HasForeignKey("AgendamentoId")
                                .HasConstraintName("fk_agendamentos_agendamentos_id");

                            b1.OwnsOne("Chronos.Agenda.Domain.Compartilhado.ObjetosValor.EnderecoAtendimento", "Endereco", b2 =>
                                {
                                    b2.Property<Guid>("LocalAtendimentoAgendamentoId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<string>("Descricao")
                                        .HasMaxLength(300)
                                        .HasColumnType("character varying(300)")
                                        .HasColumnName("local_endereco");

                                    b2.Property<byte>("_discriminator")
                                        .HasColumnType("smallint")
                                        .HasColumnName("local_endereco__discriminator");

                                    b2.HasKey("LocalAtendimentoAgendamentoId");

                                    b2.ToTable("agendamentos");

                                    b2.WithOwner()
                                        .HasForeignKey("LocalAtendimentoAgendamentoId")
                                        .HasConstraintName("fk_agendamentos_agendamentos_id");
                                });

                            b1.Navigation("Endereco");
                        });

                    b.OwnsOne("Chronos.Agenda.Domain.Agendamentos.ObjetosValor.PeriodoAgendamento", "Periodo", b1 =>
                        {
                            b1.Property<Guid>("AgendamentoId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("FimUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("fim_utc");

                            b1.Property<DateTime>("InicioUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("inicio_utc");

                            b1.HasKey("AgendamentoId");

                            b1.HasIndex("InicioUtc", "FimUtc")
                                .HasDatabaseName("ix_agendamentos_inicio_utc_fim_utc");

                            b1.ToTable("agendamentos");

                            b1.WithOwner()
                                .HasForeignKey("AgendamentoId")
                                .HasConstraintName("fk_agendamentos_agendamentos_id");
                        });

                    b.OwnsOne("Chronos.Agenda.Domain.Agendamentos.ObjetosValor.PessoaAtendida", "PessoaAtendida", b1 =>
                        {
                            b1.Property<Guid>("AgendamentoId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("pessoa_atendida_tipo");

                            b1.HasKey("AgendamentoId");

                            b1.ToTable("agendamentos");

                            b1.WithOwner()
                                .HasForeignKey("AgendamentoId")
                                .HasConstraintName("fk_agendamentos_agendamentos_id");

                            b1.OwnsOne("Chronos.Agenda.Domain.Compartilhado.ObjetosValor.Nome", "Nome", b2 =>
                                {
                                    b2.Property<Guid>("PessoaAtendidaAgendamentoId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<string>("Valor")
                                        .IsRequired()
                                        .HasMaxLength(120)
                                        .HasColumnType("character varying(120)")
                                        .HasColumnName("pessoa_atendida_nome");

                                    b2.HasKey("PessoaAtendidaAgendamentoId");

                                    b2.ToTable("agendamentos");

                                    b2.WithOwner()
                                        .HasForeignKey("PessoaAtendidaAgendamentoId")
                                        .HasConstraintName("fk_agendamentos_agendamentos_id");
                                });

                            b1.Navigation("Nome")
                                .IsRequired();
                        });

                    b.Navigation("Auditoria")
                        .IsRequired();

                    b.Navigation("Local")
                        .IsRequired();

                    b.Navigation("Periodo")
                        .IsRequired();

                    b.Navigation("PessoaAtendida")
                        .IsRequired();

                    b.Navigation("PrecoCobrado")
                        .IsRequired();
                });

            modelBuilder.Entity("Chronos.Agenda.Domain.Disponibilidades.Entidades.DisponibilidadeSemanal", b =>
                {
                    b.HasOne("Chronos.Agenda.Domain.Organizacoes.Entidades.Organizacao", null)
                        .WithMany()
                        .HasForeignKey("OrganizacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_disponibilidades_semanais_organizacoes_organizacao_id");

                    b.HasOne("Chronos.Agenda.Domain.Profissionais.Entidades.Profissional", null)
                        .WithMany()
                        .HasForeignKey("ProfissionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_disponibilidades_semanais_profissionais_profissional_id");

                    b.OwnsOne("Chronos.Agenda.Domain.Compartilhado.ObjetosValor.Auditoria", "Auditoria", b1 =>
                        {
                            b1.Property<Guid>("DisponibilidadeSemanalId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("AtualizadoEmUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("atualizado_em_utc");

                            b1.Property<DateTime>("CriadoEmUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("criado_em_utc");

                            b1.HasKey("DisponibilidadeSemanalId");

                            b1.ToTable("disponibilidades_semanais");

                            b1.WithOwner()
                                .HasForeignKey("DisponibilidadeSemanalId")
                                .HasConstraintName("fk_disponibilidades_semanais_disponibilidades_semanais_id");
                        });

                    b.OwnsOne("Chronos.Agenda.Domain.Disponibilidades.ObjetosValor.JanelaHorario", "Janela", b1 =>
                        {
                            b1.Property<Guid>("DisponibilidadeSemanalId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<TimeOnly>("Fim")
                                .HasColumnType("time without time zone")
                                .HasColumnName("hora_fim");

                            b1.Property<TimeOnly>("Inicio")
                                .HasColumnType("time without time zone")
                                .HasColumnName("hora_inicio");

                            b1.HasKey("DisponibilidadeSemanalId");

                            b1.ToTable("disponibilidades_semanais");

                            b1.WithOwner()
                                .HasForeignKey("DisponibilidadeSemanalId")
                                .HasConstraintName("fk_disponibilidades_semanais_disponibilidades_semanais_id");
                        });

                    b.Navigation("Auditoria")
                        .IsRequired();

                    b.Navigation("Janela")
                        .IsRequired();
                });

            modelBuilder.Entity("Chronos.Agenda.Domain.Organizacoes.Entidades.Organizacao", b =>
                {
                    b.OwnsOne("Chronos.Agenda.Domain.Compartilhado.ObjetosValor.Auditoria", "Auditoria", b1 =>
                        {
                            b1.Property<Guid>("OrganizacaoId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("AtualizadoEmUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("atualizado_em_utc");

                            b1.Property<DateTime>("CriadoEmUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("criado_em_utc");

                            b1.HasKey("OrganizacaoId");

                            b1.ToTable("organizacoes");

                            b1.WithOwner()
                                .HasForeignKey("OrganizacaoId")
                                .HasConstraintName("fk_organizacoes_organizacoes_id");
                        });

                    b.OwnsOne("Chronos.Agenda.Domain.Compartilhado.ObjetosValor.EnderecoAtendimento", "EnderecoPrestador", b1 =>
                        {
                            b1.Property<Guid>("OrganizacaoId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Descricao")
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("endereco_prestador");

                            b1.Property<byte>("_discriminator")
                                .HasColumnType("smallint")
                                .HasColumnName("endereco_prestador__discriminator");

                            b1.HasKey("OrganizacaoId");

                            b1.ToTable("organizacoes");

                            b1.WithOwner()
                                .HasForeignKey("OrganizacaoId")
                                .HasConstraintName("fk_organizacoes_organizacoes_id");
                        });

                    b.OwnsOne("Chronos.Agenda.Domain.Organizacoes.ObjetosValor.FusoHorario", "FusoHorario", b1 =>
                        {
                            b1.Property<Guid>("OrganizacaoId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Identificador")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("fuso_horario");

                            b1.Property<byte>("_discriminator")
                                .HasColumnType("smallint")
                                .HasColumnName("fuso_horario__discriminator");

                            b1.HasKey("OrganizacaoId");

                            b1.ToTable("organizacoes");

                            b1.WithOwner()
                                .HasForeignKey("OrganizacaoId")
                                .HasConstraintName("fk_organizacoes_organizacoes_id");
                        });

                    b.OwnsOne("Chronos.Agenda.Domain.Organizacoes.ObjetosValor.NomeOrganizacao", "Nome", b1 =>
                        {
                            b1.Property<Guid>("OrganizacaoId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("nome");

                            b1.HasKey("OrganizacaoId");

                            b1.ToTable("organizacoes");

                            b1.WithOwner()
                                .HasForeignKey("OrganizacaoId")
                                .HasConstraintName("fk_organizacoes_organizacoes_id");
                        });

                    b.Navigation("Auditoria")
                        .IsRequired();

                    b.Navigation("EnderecoPrestador");

                    b.Navigation("FusoHorario");

                    b.Navigation("Nome")
                        .IsRequired();
                });

            modelBuilder.Entity("Chronos.Agenda.Domain.Profissionais.Entidades.Profissional", b =>
                {
                    b.HasOne("Chronos.Agenda.Domain.Organizacoes.Entidades.Organizacao", null)
                        .WithMany()
                        .HasForeignKey("OrganizacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_profissionais_organizacoes_organizacao_id");

                    b.OwnsOne("Chronos.Agenda.Domain.Compartilhado.ObjetosValor.Auditoria", "Auditoria", b1 =>
                        {
                            b1.Property<Guid>("ProfissionalId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("AtualizadoEmUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("atualizado_em_utc");

                            b1.Property<DateTime>("CriadoEmUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("criado_em_utc");

                            b1.HasKey("ProfissionalId");

                            b1.ToTable("profissionais");

                            b1.WithOwner()
                                .HasForeignKey("ProfissionalId")
                                .HasConstraintName("fk_profissionais_profissionais_id");
                        });

                    b.OwnsOne("Chronos.Agenda.Domain.Compartilhado.ObjetosValor.Nome", "Nome", b1 =>
                        {
                            b1.Property<Guid>("ProfissionalId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("nome");

                            b1.HasKey("ProfissionalId");

                            b1.ToTable("profissionais");

                            b1.WithOwner()
                                .HasForeignKey("ProfissionalId")
                                .HasConstraintName("fk_profissionais_profissionais_id");
                        });

                    b.Navigation("Auditoria")
                        .IsRequired();

                    b.Navigation("Nome")
                        .IsRequired();
                });

            modelBuilder.Entity("Chronos.Agenda.Domain.Servicos.Entidades.Servico", b =>
                {
                    b.HasOne("Chronos.Agenda.Domain.Organizacoes.Entidades.Organizacao", null)
                        .WithMany()
                        .HasForeignKey("OrganizacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_servicos_organizacoes_organizacao_id");

                    b.HasOne("Chronos.Agenda.Domain.Profissionais.Entidades.Profissional", null)
                        .WithMany()
                        .HasForeignKey("ProfissionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_servicos_profissionais_profissional_id");

                    b.OwnsOne("Chronos.Agenda.Domain.Compartilhado.ObjetosValor.Auditoria", "Auditoria", b1 =>
                        {
                            b1.Property<Guid>("ServicoId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("AtualizadoEmUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("atualizado_em_utc");

                            b1.Property<DateTime>("CriadoEmUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("criado_em_utc");

                            b1.HasKey("ServicoId");

                            b1.ToTable("servicos");

                            b1.WithOwner()
                                .HasForeignKey("ServicoId")
                                .HasConstraintName("fk_servicos_servicos_id");
                        });

                    b.OwnsOne("Chronos.Agenda.Domain.Servicos.ObjetosValor.PrecoServico", "Preco", b1 =>
                        {
                            b1.Property<Guid>("ServicoId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("preco");

                            b1.HasKey("ServicoId");

                            b1.ToTable("servicos");

                            b1.WithOwner()
                                .HasForeignKey("ServicoId")
                                .HasConstraintName("fk_servicos_servicos_id");
                        });

                    b.OwnsOne("Chronos.Agenda.Domain.Servicos.ObjetosValor.DuracaoServico", "Duracao", b1 =>
                        {
                            b1.Property<Guid>("ServicoId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<TimeSpan>("Valor")
                                .HasColumnType("interval")
                                .HasColumnName("duracao");

                            b1.HasKey("ServicoId");

                            b1.ToTable("servicos");

                            b1.WithOwner()
                                .HasForeignKey("ServicoId")
                                .HasConstraintName("fk_servicos_servicos_id");
                        });

                    b.OwnsOne("Chronos.Agenda.Domain.Servicos.ObjetosValor.NomeServico", "Nome", b1 =>
                        {
                            b1.Property<Guid>("ServicoId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("nome");

                            b1.HasKey("ServicoId");

                            b1.ToTable("servicos");

                            b1.WithOwner()
                                .HasForeignKey("ServicoId")
                                .HasConstraintName("fk_servicos_servicos_id");
                        });

                    b.Navigation("Auditoria")
                        .IsRequired();

                    b.Navigation("Duracao")
                        .IsRequired();

                    b.Navigation("Nome")
                        .IsRequired();

                    b.Navigation("Preco")
                        .IsRequired();
                });

            modelBuilder.Entity("Chronos.Agenda.Infrastructure.Compartilhado.MembroOrganizacao", b =>
                {
                    b.HasOne("Chronos.Agenda.Domain.Organizacoes.Entidades.Organizacao", null)
                        .WithMany()
                        .HasForeignKey("OrganizacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_membros_organizacao_organizacoes_organizacao_id");

                    b.HasOne("Chronos.Agenda.Infrastructure.Identity.UsuarioIdentity", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_membros_organizacao_usuarios_usuario_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Chronos.Agenda.Infrastructure.Identity.PapelIdentity", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_claims_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Chronos.Agenda.Infrastructure.Identity.UsuarioIdentity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_claims_usuarios_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Chronos.Agenda.Infrastructure.Identity.UsuarioIdentity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_logins_usuarios_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Chronos.Agenda.Infrastructure.Identity.PapelIdentity", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("Chronos.Agenda.Infrastructure.Identity.UsuarioIdentity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_usuarios_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Chronos.Agenda.Infrastructure.Identity.UsuarioIdentity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_usuarios_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
